// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Ware struct {
	ID       int64
	Name     string
	Category sql.NullString
	MinPrice int64
	MaxPrice int64
	Volume   int64
}
