// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wares.sql

package database

import (
	"context"
)

const getAllWares = `-- name: GetAllWares :many
SELECT id, name, category, min_price, max_price, volume FROM wares
`

func (q *Queries) GetAllWares(ctx context.Context) ([]Ware, error) {
	rows, err := q.db.QueryContext(ctx, getAllWares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ware
	for rows.Next() {
		var i Ware
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.MinPrice,
			&i.MaxPrice,
			&i.Volume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
